spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://8.130.176.200:8006/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 8.130.176.200
    #password: root@123456
    port: 8009
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true
  session:
    store-type: redis
  zipkin:
    base-url: http://8.130.176.200:9411/ # zipkin 服务器的地址
    # 关闭服务发现，否则 Spring Cloud 会把 zipkin 的 url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用 http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为 100%，默认为 0.1，即 10%
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10001
logging:
  level:
    com.zxl.gulimall: debug
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
