apiVersion: apps/v1
kind: Deployment
metadata:
  name: gulimall-cart
  namespace: gulimall
  labels:
    app: gulimall-cart
# 规格
spec:
  # 副本数
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-cart
  template:
    metadata:
      labels:
        app: gulimall-cart
    spec:
      containers:
        - name: gulimall-cart
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
kind: Service
apiVersion: v1
metadata:
  name: gulimall-cart
  namespace: gulimall
  labels:
    app: gulimall-cart
spec:
  ports:
    - name: http-8080
      protocol: TCP
      # service端口
      port: 8080
      # 容器端口
      targetPort: 8080
      # 外部端口
      nodePort: 30003

  selector:
    app: gulimall-cart
  type: NodePort
  sessionAffinity: None

