spring:
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  session:
    store-type: redis
  redis:
    host: 8.130.176.200
    #password: root@123456
    port: 8009
server:
  port: 12000
