spring:
  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  session:
    store-type: redis
  redis:
    host: 8.130.176.200
    #password: root@123456
    port: 8009
  zipkin:
    base-url: http://8.130.176.200:9411/ # zipkin 服务器的地址
    # 关闭服务发现，否则 Spring Cloud 会把 zipkin 的 url 当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用 http 的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集率为 100%，默认为 0.1，即 10%
server:
  port: 12000
