server:
  port: 88
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      routes:
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/thirdParty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=zxl1027.com,item.zxl1027.com
        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.zxl1027.com
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.zxl1027.com
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.zxl1027.com
        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.zxl1027.com
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.zxl1027.com
## 前端/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree

