spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
alibaba:
  cloud:
    access-key:
    secret-key:
    oss:
      endpoint:
server:
  port: 30000
